from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QHBoxLayout
from PyQt6.QtWidgets import QFrame, QWidget, QHeaderView


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 600)
        Form.setStyleSheet("""
                QWidget {
                        background-color: white;
                }
                QLabel {
                        font-size: 15px;
                        color: black;
                }
                QPushButton {
                        font-size: 16px;
                        padding: 10px;
                        background-color: purple;
                        color: white;
                           border: none;
                           border-radius: 2px;
                }
                QTableWidget {
                        border: 1px solid black;
                }
                QSpinBox, QLineEdit, QComboBox {
                        padding: 7px;
                        font-size: 14px;
                        color: black;
                        border: 1px solid purple;
                        border-radius: 2px;
                        min-width: 200px;
                         max-width: 200px;
                }

                QSpinBox::down-button, QSpinBox::up-button, QComboBox::drop-down {
                        width: 20px;
                        background: none;
                        border: none;
                }

                QSpinBox::up-arrow {
                        image: url("C:/Users/James Matata/Desktop/CodeWizard/Python_Programming/Learning_Python_GUIs_with_PyQt6/MarksManager/files/up.png");
                        width: 20px;
                        height: 20px;
                }

                QSpinBox::down-arrow {
                        image: url("C:/Users/James Matata/Desktop/CodeWizard/Python_Programming/Learning_Python_GUIs_with_PyQt6/MarksManager/files/down.png");
                        width: 20px;
                        height: 20px;
                }

                QComboBox::down-arrow {
                        width: 20px;
                        height: 20px;
                        image: url("C:/Users/James Matata/Desktop/CodeWizard/Python_Programming/Learning_Python_GUIs_with_PyQt6/MarksManager/files/down.png");
                }
        """)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.inner_new_student_page = QtWidgets.QWidget()
        self.inner_new_student_page.setObjectName("page")
        self.inner_new_student_page.setFixedWidth(400)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_4.setStyleSheet("font-size: 20px; color: purple; font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_3.addWidget(self.label_4)
        line = QFrame()
        line.setFrameShape(QFrame.Shape.HLine)
        line.setFrameShadow(QFrame.Shadow.Sunken)
        self.verticalLayout_3.addWidget(line)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.new_full_name = QtWidgets.QLineEdit(parent=self.inner_new_student_page)
        self.new_full_name.setObjectName("new_full_name")
        self.horizontalLayout_12.addWidget(self.new_full_name)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.new_adm_no = QtWidgets.QLineEdit(parent=self.inner_new_student_page)
        self.new_adm_no.setObjectName("new_adm_no")
        self.horizontalLayout_11.addWidget(self.new_adm_no)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.new_class = QtWidgets.QComboBox(parent=self.inner_new_student_page)
        self.new_class.addItems(["Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8"])
        self.new_class.setObjectName("new_class")
        self.horizontalLayout_10.addWidget(self.new_class)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.new_math = QtWidgets.QSpinBox(parent=self.inner_new_student_page)
        self.new_math.setObjectName("new_math")
        self.horizontalLayout_9.addWidget(self.new_math)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.new_eng = QtWidgets.QSpinBox(parent=self.inner_new_student_page)
        self.new_eng.setObjectName("new_eng")
        self.horizontalLayout_8.addWidget(self.new_eng)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.new_kisw = QtWidgets.QSpinBox(parent=self.inner_new_student_page)
        self.new_kisw.setObjectName("new_kisw")
        self.horizontalLayout_7.addWidget(self.new_kisw)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.new_sci = QtWidgets.QSpinBox(parent=self.inner_new_student_page)
        self.new_sci.setObjectName("new_sci")
        self.horizontalLayout_6.addWidget(self.new_sci)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.new_ss = QtWidgets.QSpinBox(parent=self.inner_new_student_page)
        self.new_ss.setObjectName("new_ss")
        self.horizontalLayout_5.addWidget(self.new_ss)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(parent=self.inner_new_student_page)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.new_cre = QtWidgets.QSpinBox(parent=self.inner_new_student_page)
        self.new_cre.setObjectName("new_cre")
        self.horizontalLayout_4.addWidget(self.new_cre)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.new_cancel = QtWidgets.QPushButton(parent=self.inner_new_student_page)
        self.new_cancel.setObjectName("new_cancel")
        self.new_cancel.setStyleSheet("background-color: red;")
        self.new_cancel.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.horizontalLayout_13.addWidget(self.new_cancel)
        self.new_save = QtWidgets.QPushButton(parent=self.inner_new_student_page)
        self.new_save.setObjectName("new_save")
        self.horizontalLayout_13.addWidget(self.new_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        spacerItemr = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItemr)
        self.inner_new_student_page.setLayout(self.verticalLayout_2)
        self.new_student_page = QtWidgets.QWidget()
        self.new_student_page_layout = QtWidgets.QHBoxLayout(self.new_student_page)
        self.new_student_page_layout.addWidget(self.inner_new_student_page)
        self.stackedWidget.addWidget(self.new_student_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.page_2)
        self.label.setStyleSheet("font-size: 18px; color: purple; font-weight: bold;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFixedWidth(200)
        self.pushButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        line56 = QFrame()
        line56.setFrameShape(QFrame.Shape.HLine)
        line56.setFrameShadow(QFrame.Shadow.Sunken)
        self.verticalLayout.addWidget(line56)
        self.horizontalLayout78 = QHBoxLayout()
        self.filter_input = QtWidgets.QLineEdit()
        self.filter_input.setPlaceholderText("Search students by Name.....")
        self.filter_input.setStyleSheet("width: 800px;")
        self.filter_button = QtWidgets.QPushButton('Filter')
        self.filter_button.setFixedWidth(200)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout78.addWidget(self.filter_input)
        self.horizontalLayout78.addItem(spacerItem25)
        self.horizontalLayout78.addWidget(self.filter_button)
        self.verticalLayout.addLayout(self.horizontalLayout78)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.verticalHeader().setDefaultSectionSize(45)
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setHorizontalHeaderLabels([
            "Id", "Full Name", "Admission No.", "Class", "Mathematics", 
            "English", "Kiswahili", "Science", "Social Studies", "C.R.E", "Action"
        ])
        header = self.tableWidget.horizontalHeader()
        for col in range(10):
            header.setSectionResizeMode(col, QHeaderView.ResizeMode.Stretch)
        header.setSectionResizeMode(10, QHeaderView.ResizeMode.Interactive)

        self.tableWidget.setColumnWidth(10, 200)
        self.verticalLayout.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page_2)
        self.inner_edit_student_page = QtWidgets.QWidget()
        self.inner_edit_student_page.setObjectName("page_3")
        self.inner_edit_student_page.setFixedWidth(400)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_14.setStyleSheet("font-size: 20px; color: purple; font-weight: bold;")
        self.label_14.setObjectName("label_14")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_5.addWidget(self.label_14)
        line = QFrame()
        line.setFrameShape(QFrame.Shape.HLine)
        line.setFrameShadow(QFrame.Shadow.Sunken)
        self.verticalLayout_5.addWidget(line)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.edit_full_name = QtWidgets.QLineEdit(parent=self.inner_edit_student_page)
        self.edit_full_name.setObjectName("edit_full_name")
        self.horizontalLayout_15.addWidget(self.edit_full_name)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.edit_adm_no = QtWidgets.QLineEdit(parent=self.inner_edit_student_page)
        self.edit_adm_no.setObjectName("edit_adm_no")
        self.horizontalLayout_16.addWidget(self.edit_adm_no)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.edit_class = QtWidgets.QComboBox(parent=self.inner_edit_student_page)
        self.edit_class.setObjectName("edit_class")
        self.edit_class.addItems(["Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8"])
        self.horizontalLayout_17.addWidget(self.edit_class)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem13)
        self.edit_math = QtWidgets.QSpinBox(parent=self.inner_edit_student_page)
        self.edit_math.setObjectName("edit_math")
        self.horizontalLayout_18.addWidget(self.edit_math)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem14)
        self.edit_eng = QtWidgets.QSpinBox(parent=self.inner_edit_student_page)
        self.edit_eng.setObjectName("edit_eng")
        self.horizontalLayout_19.addWidget(self.edit_eng)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem15)
        self.edit_kisw = QtWidgets.QSpinBox(parent=self.inner_edit_student_page)
        self.edit_kisw.setObjectName("edit_kisw")
        self.horizontalLayout_20.addWidget(self.edit_kisw)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.edit_sci = QtWidgets.QSpinBox(parent=self.inner_edit_student_page)
        self.edit_sci.setObjectName("edit_sci")
        self.horizontalLayout_21.addWidget(self.edit_sci)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem17)
        self.edit_ss = QtWidgets.QSpinBox(parent=self.inner_edit_student_page)
        self.edit_ss.setObjectName("edit_ss")
        self.horizontalLayout_22.addWidget(self.edit_ss)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(parent=self.inner_edit_student_page)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem18)
        self.edit_cre = QtWidgets.QSpinBox(parent=self.inner_edit_student_page)
        self.edit_cre.setObjectName("edit_cre")
        self.horizontalLayout_23.addWidget(self.edit_cre)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.edit_cancel = QtWidgets.QPushButton(parent=self.inner_edit_student_page)
        self.edit_cancel.setObjectName("edit_cancel")
        self.edit_cancel.setStyleSheet("background-color: red;")
        self.edit_cancel.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.horizontalLayout_24.addWidget(self.edit_cancel)
        self.edit_save = QtWidgets.QPushButton(parent=self.inner_edit_student_page)
        self.edit_save.setObjectName("edit_save")
        self.horizontalLayout_24.addWidget(self.edit_save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        spacerIteml = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerIteml)
        self.inner_edit_student_page.setLayout(self.verticalLayout_4)
        self.edit_student_page = QtWidgets.QWidget()
        self.edit_student_page_layout = QtWidgets.QHBoxLayout(self.edit_student_page)
        self.edit_student_page_layout.addWidget(self.inner_edit_student_page)
        self.stackedWidget.addWidget(self.edit_student_page)
        self.horizontalLayout_2.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Student Marks Manager"))
        self.label_4.setText(_translate("Form", "Add New Student Marks"))
        self.label_5.setText(_translate("Form", "Full Name"))
        self.label_6.setText(_translate("Form", "Adminsion No."))
        self.label_7.setText(_translate("Form", "Class"))
        self.label_8.setText(_translate("Form", "Mathematics"))
        self.label_9.setText(_translate("Form", "English"))
        self.label_10.setText(_translate("Form", "Kiswahili"))
        self.label_11.setText(_translate("Form", "Science"))
        self.label_12.setText(_translate("Form", "Social Studies"))
        self.label_13.setText(_translate("Form", "C.R.E"))
        self.new_cancel.setText(_translate("Form", "Cancel"))
        self.new_save.setText(_translate("Form", "Save"))
        self.label.setText(_translate("Form", "Student Marks"))
        self.pushButton.setText(_translate("Form", "Add New Student"))
        self.label_14.setText(_translate("Form", "Edit Student Marks"))
        self.label_15.setText(_translate("Form", "Full Name"))
        self.label_16.setText(_translate("Form", "Adminsion No."))
        self.label_17.setText(_translate("Form", "Class"))
        self.label_18.setText(_translate("Form", "Mathematics"))
        self.label_19.setText(_translate("Form", "English"))
        self.label_20.setText(_translate("Form", "Kiswahili"))
        self.label_21.setText(_translate("Form", "Science"))
        self.label_22.setText(_translate("Form", "Social Studies"))
        self.label_23.setText(_translate("Form", "C.R.E"))
        self.edit_cancel.setText(_translate("Form", "Cancel"))
        self.edit_save.setText(_translate("Form", "Save"))
